- id: "xxxxxxxx"
  pwd: "xxxxxxxx"
  email_to: "xxxxxxxx@xxxx.xxx"
  campus: "xxx"
  county: "xxx"
  address: "xxx"

- id: "xxxxxxxx"
  pwd: "xxxxxxxx"
  email_to: "xxxxxxxx@xxxx.xxx"
  campus: "xxx"
  county: "xxx"
  address: "xxx"
