report:
  send_email: true                       // 是否发送每日一报是否成功的提醒邮件

  morning_hour: 7                      // 早上填报的时间
  morning_minute: 15

  night_hour: 20                         // 晚上填报的时间
  night_minute: 45

  temperature: 36.5                    // 温度


manager:
  send_email: true                                      // 是否发送每天的日志给程序管理员
  email_to: "xxx@xxx.xxx"                           // 接收日志的邮箱账号
  hour: 22                                                   // 发送日志的时间
  minute: 30


email:
  from: "xxx@xxx.xxx"                             // 用于发送邮件的账号
  username: "xxx@xxx.xxx"                     // 用于发送邮件的账号
  password: "xxx"                                   // 邮件服务器的密钥
  smtp: "smtp.xxx.xxx"
  port: 465
